spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lanyueyang@01
    url: jdbc:mysql://127.0.0.1/gym?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
logging:
  path: d:/
  level: trace
  config: classpath:logback-spring-dev.xml
server:
  port: 88

filePath: D:\files

test:
      name : jerry
      age: 19

