spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.cfg.DefaultNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    default-property-inclusion: non_null
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
# jackson:
#   default-property-inclusion: non_null
# redis:
#   host: 192.168.30.113
#   port: 6379

#server:
#   context-path: /index
#   error:
#     path: /error


mail_appid : 10034
mail_appkey : 6e88cf3e26b914c70b9e57b5ebb26b21
mail_signtype : md5
msg_appid : 13698
msg_appkey : 3877871b96eac711ed8a76e286df30bc
msg_signtype : normal


##httpclient
#最大连接数
http:
    maxTotal : 50000
#并发数
    defaultMaxPerRoute : 10000
#创建连接的最长时间
    connectTimeout: 20000
#从连接池中获取到连接的最长时间
    connectionRequestTimeout: 20000
#数据传输的最长时间
    socketTimeout: 30000
#提交请求前测试连接是否可用
    staleConnectionCheckEnabled: true
server:
  session:
    timeout: -1


coupon:
  useCode: Sw6cWT88
  useCode_2: TLG520
  useCode_3: TLG2018

wechat:
  mpAppId: wx03701da4fa8af499
  mpAppSecret: 6c25e4c347ca3802758980b5f4704e61
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1499411852
  mchKey: 17B20EDF2C63A54D07A284AF637763C0
  keyPath: /home/tony/文档/mchKey/cert/apiclient_cert.p12
  notifyUrl: http://bridge.natapp1.cc/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: https://member.thelittlegym.com.cn/wechat/userInfo
  wechatOpenAuthorize: https://member.thelittlegym.com.cn
  sell: https://member.thelittlegym.com.cn









