spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lanyueyang@01
    url: jdbc:mysql://101.37.160.171/gym?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
logging:
  path: E:\tomcat8\apache-tomcat-8.0.42\logs\mylogs
  level: trace

filePath: E:\tomcat8\apache-tomcat-8.0.42\files