spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lanyueyang@01
    url: jdbc:mysql://101.37.160.171/gym?characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://127.0.0.1/gym?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
logging:
  path: E:\log
  level: trace
  config: classpath:logback-spring.xml
server:
  port: 8888

filePath: E:\log\files

test:
      name : jerry
      age: 19

